# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30da7265ab5367df792bf2bf4e2eaae0cb9a120eb332cb88796684d216f88240c9046e029bec615752543519b5f32c971d61a365d95e9ebe801492f44d072ae8

test:
  secret_key_base: 568fa48c24189ae1b05a8171f104a8827582f9d0e37ace83b693bfc790ef70471f2e99273a2145b3204703f04405d814b47cfd4de130d85456c08d1c0a5d7433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
